services:
  mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: user
      MYSQL_PASSWORD: default
      MYSQL_DATABASE: bank-app
    ports:
      - 3306:3306
  app:
    build: .
    ports:
      - 8080:8080





